### ISSUE TITLE
Unable to connect to Databricks from Github Actions using Windows runner OS

### ISSUE THREAD

**Issue by alexmalins** [databricks/databricks-sql-python#431]
I'm trying to set up Github Actions for CI for [harlequin-databricks](https://github.com/alexmalins/harlequin-databricks/pull/11), but whenever setting one of the Windows images as the OS for the Github Action, the Action hangs & is unable to connect to Databricks & initiate a SQL query.

Have tried both OAuth M2M and PAT as auth methods, and setting `_tls_no_verify=True` in `sql.connect()` without success.

Running the Action using an Ubuntu or MacOS image works fine, so this is specifically a Windows issue. It is also specific to Github Actions, as running the MWE below works fine on a windows laptop. So potentially this is a Github Actions issue not one with this package.

Does anyone have any ideas what's going on?

```
from databricks.sdk.core import Config, oauth_service_principal
from databricks import sql
import os

def credential_provider():
    config = Config(
        host = os.getenv("DATABRICKS_HOST"),
        client_id = os.getenv("DATABRICKS_CLIENT_ID"),
        client_secret = os.getenv("DATABRICKS_CLIENT_SECRET"),
    )
    return oauth_service_principal(config)

def main():
    with sql.connect(
        server_hostname = f'https://{os.getenv("DATABRICKS_HOST")}',
        http_path = os.getenv("DATABRICKS_HTTP_PATH"),
        credentials_provider = credential_provider,
        #access_token = os.getenv("DATABRICKS_TOKEN"),
        #_tls_no_verify=True,
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1")
            result = cursor.fetchall_arrow()
            print(result)

if __name__ == "__main__":
    main()
```

**Comment by alexmalins** [comment]
hey folks - this is resolved. It was a GitHub Actions issue relating to setting bash as the shell on the windows runner*. With bash set the Action always hangs upon the first attempt to connect to Databricks. Using the default windows shell everything works fine.

*setting `shell: bash` for windows is a requirement of [snok/poetry](https://github.com/snok/install-poetry?tab=readme-ov-file#running-on-windows) install action. I can work around this issueby not using that poetry install action.

This is a minimal code example of the issue for visibility:

Action:
```
name: windows-latest with shell bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows_latest_bash:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 5

    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Run connection
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          #DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          pip install databricks-sql-connector databricks-sdk
          python db_test.py
```

Running a simple Databricks connection test script `db_test.py`:
```
from databricks.sdk.core import Config, oauth_service_principal
from databricks import sql
import os

def credential_provider():
    config = Config(
        host = os.getenv("DATABRICKS_HOST"),
        client_id = os.getenv("DATABRICKS_CLIENT_ID"),
        client_secret = os.getenv("DATABRICKS_CLIENT_SECRET"),
    )
    return oauth_service_principal(config)

def main():
    with sql.connect(
        server_hostname = f'https://{os.getenv("DATABRICKS_HOST")}',
        http_path = os.getenv("DATABRICKS_HTTP_PATH"),
        credentials_provider = credential_provider,
        #access_token = os.getenv("DATABRICKS_TOKEN"),
    ) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1")
            result = cursor.fetchall_arrow()
            print(result)

if __name__ == "__main__":
    main()
```

Commenting out these lines in the yml will result in a successful action run:
```
    defaults:
      run:
        shell: bash
```
if included however the Action will hang upon Databricks connect
